version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www
    ports:
      - 8080:80
    depends_on:
      - app
    container_name: app-nginx
  
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: app
  
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./.tmp/db/data:/var/lib/mysql
      - ./database/migrations/sql:/docker-entrypoint-initdb.d
    environment:  
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_task
    container_name: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    container_name: app-adminer